version: "~> 1.0"
language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
          - unixodbc-dev
          - odbc-postgresql
          - libsqliteodbc
          - postgresql-10
        postgresql: 10
      services:
        - docker
        - postgresql
      env: ODBC_SYS_STATIC_PATH=/usr/lib/x86_64-linux-gnu/ POSTGRES_DRIVER=/usr/lib/x86_64-linux-gnu/odbc/psqlodbca.so SQLITE_DRIVER=/usr/lib/x86_64-linux-gnu/odbc/libsqlite3odbc.so
      before_script:
        - sudo -u postgres psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
        - sudo -u postgres createdb -O foo foo
      script:
        - cargo test -- --nocapture || travis_terminate 1
        - docker build . -t wait_for_db || travis_terminate 1
        - docker run --name wait_for_db wait_for_db --help || travis_terminate 1
        - docker cp wait_for_db:/wait_for_db wait-for-db-linux-x86
      deploy:
        provider: releases
        edge: true
        file: wait-for-db-linux-x86
        skip_cleanup: true
        draft: true
        overwrite: true
        on:
          tags: true

    - os: osx
      osx_image: xcode11.6
      addons:
        homebrew:
          packages:
          - psqlodbc
          - sqliteodbc
          - postgresql
      env: SQLITE_DRIVER=/usr/local/opt/sqliteodbc/lib/libsqlite3odbc.dylib POSTGRES_DRIVER=/usr/local/opt/psqlodbc/lib/psqlodbca.so HOMEBREW_NO_INSTALL_CLEANUP=1
      before_script:
        - pg_ctl -D /usr/local/var/postgres start
        - psql postgres -c "CREATE USER foo WITH PASSWORD 'bar';"
        - createdb -O foo foo
      script:
        - cargo test -- --nocapture || travis_terminate 1
        - cargo build --release || travis_terminate 1
        - strip target/release/wait_for_db || travis_terminate 1
        - otool -L target/release/wait_for_db || travis_terminate 1
        - mv target/release/wait_for_db wait-for-db-osx || travis_terminate 1
      deploy:
        provider: releases
        edge: true
        file: wait-for-db-osx
        skip_cleanup: true
        draft: true
        overwrite: true
        on:
          tags: true

env:
  global:
    - POSTGRES_SERVER=localhost
    - POSTGRES_PORT=5432
    - POSTGRES_USERNAME=foo
    - POSTGRES_PASSWORD=bar
    - RUST_BACKTRACE=1