language: rust
dist: bionic

cache: cargo

services:
  - docker
  - postgresql

addons:
  apt:
    packages:
    - unixodbc-dev
    - odbc-postgresql
    - libsqliteodbc
    - postgresql-10
  postgresql: 10

before_script:
  - sudo -u postgres psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

script:
  - cargo test -- --nocapture || travis_terminate 1
  - docker build . -t wait_for_db || travis_terminate 1
  - docker run --rm wait_for_db --help || travis_terminate 1

env:
  global:
    - ODBC_SYS_STATIC_PATH=/usr/lib/x86_64-linux-gnu/
    - POSTGRES_SERVER=localhost
    - POSTGRES_PORT=5432
    - POSTGRES_USERNAME=foo
    - POSTGRES_PASSWORD=bar
    - RUST_BACKTRACE=1
    - POSTGRES_DRIVER=/usr/lib/x86_64-linux-gnu/odbc/psqlodbca.so
    - SQLITE_DRIVER=/usr/lib/x86_64-linux-gnu/odbc/libsqlite3odbc.so