language: rust
dist: bionic

cache: cargo

services:
  - docker
  - postgresql

addons:
  apt:
    packages:
    - unixodbc-dev
    - odbc-postgresql
    - libsqliteodbc
    - postgresql-10
  postgresql: 10

before_script:
  - sudo -u postgres psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  - sudo -u postgres createdb -O foo foo

script:
  - cargo test -- --nocapture || travis_terminate 1
  - docker build . -t wait_for_db || travis_terminate 1
  - docker run --name wait_for_db wait_for_db --help || travis_terminate 1
  - docker cp wait_for_db:/wait_for_db .

env:
  global:
    - ODBC_SYS_STATIC_PATH=/usr/lib/x86_64-linux-gnu/
    - POSTGRES_SERVER=localhost
    - POSTGRES_PORT=5433
    - POSTGRES_USERNAME=foo
    - POSTGRES_PASSWORD=bar
    - PGPORT=5433
    - RUST_BACKTRACE=1
    - POSTGRES_DRIVER=/usr/lib/x86_64-linux-gnu/odbc/psqlodbca.so
    - SQLITE_DRIVER=/usr/lib/x86_64-linux-gnu/odbc/libsqlite3odbc.so

deploy:
  provider: releases
  api_key:
    secure: "EJnploggtmiPSTZdGRK4aF0morZwWOzSC9bjLqaSRrRkKRUl4dFOvibKOuPrK/xndoDmiB6YkPTR6pgIDbUtlT22IFexcjcru54VmP2oYeSCfS/rFeqZq5AS71t+eEn00lUrdqMO7tOuQNV5Np6d6TdwY6EYdX9JTlnbknkvhJ+7gsv1wmEbtkaSrcXvku11gzPNySafvxEZuufFGjTTVhCVL7h282NeCUA7+lBeh1LvEobTdyfCWkG039vMO2iyCffAF1URBsp2/Tk+NwIl6epaKrsFZg4eA5tgLzXp3K6TVGt24OMOlp99vs2X4GJl4Q+bK1cYKw1Nth1t1DvmUhV9aRmrSDJIrZJW+HEzD1SkQQ9hovdRnkEf7du7Xxepe6X6I9U7YkVlboMy0xBj33SfLGsgEs/slWYh3PbU/smwHIE7TO8iJDWQ052I5F+e+Jrqme9+D7hBFk7EHDCj3YZtgDLphvruiBroxX7JI4A+wo6GmicMni3ZU3q+pxXAN519Gm+4VHcqpCboY12XJowNP2mJ8ehNSkDp5Qh0uZn/CScSIGE7CTuEntFoG/P5/6cy0T1zbdulj5o4Lv2p6fPHujyTCgw5M8SZIpKL4qc9BYoeRmz5McMFJNLBeTuNqtgjktTNw4vwX0mHdLqmXnw72mvp9BYxf4FPRwPsA4g="
  file: "wait_for_db"
  skip_cleanup: true
  draft: true
  overwrite: true
  # on:
  #   tags: true