on:
    push:
        branches:
            - main
    pull_request:

name: macOS

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - name: Install Homebrew dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install psqlodbc sqliteodbc postgresql
      - name: Create test db/user
        run: |
          pg_ctl -D /usr/local/var/postgres start
          psql postgres -c "CREATE USER foo WITH PASSWORD 'bar';"
          createdb -O foo foo
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Tests
        env:
          SQLITE_DRIVER: /usr/local/opt/sqliteodbc/lib/libsqlite3odbc.dylib
          POSTGRES_DRIVER: /usr/local/opt/psqlodbc/lib/psqlodbca.so
          POSTGRES_SERVER: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USERNAME: foo
          POSTGRES_PASSWORD: bar
          RUST_BACKTRACE: 1          
        run: cargo test -- --nocapture
      - name: Build release
        run: cargo build --release
      - run: |
          otool -L target/release/wait_for_db
          if otool -L target/release/wait_for_db | grep -q /usr/local; then
            echo Found local non-static refs!            
            exit 1
          fi
          strip target/release/wait_for_db
          mv target/release/wait_for_db wait-for-db-osx